// Code generated by "go-enum -type=QueryRunnerType -yaml -trimprefix QueryRunnerType"; DO NOT EDIT.

// Install go-enum by `go get -u github.com/searKing/golang/tools/go-enum`
package prepalert

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QueryRunnerTypeRedshiftData-1]
}

const _QueryRunnerType_name = "RedshiftData"

var _QueryRunnerType_index = [...]uint8{0, 12}

func _() {
	var _nil_QueryRunnerType_value = func() (val QueryRunnerType) { return }()

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_QueryRunnerType_value
}

func (i QueryRunnerType) String() string {
	i -= 1
	if i < 0 || i >= QueryRunnerType(len(_QueryRunnerType_index)-1) {
		return "QueryRunnerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _QueryRunnerType_name[_QueryRunnerType_index[i]:_QueryRunnerType_index[i+1]]
}

// New returns a pointer to a new addr filled with the QueryRunnerType value passed in.
func (i QueryRunnerType) New() *QueryRunnerType {
	clone := i
	return &clone
}

var _QueryRunnerType_values = []QueryRunnerType{1}

var _QueryRunnerType_name_to_values = map[string]QueryRunnerType{
	_QueryRunnerType_name[0:12]: 1,
}

// ParseQueryRunnerTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseQueryRunnerTypeString(s string) (QueryRunnerType, error) {
	if val, ok := _QueryRunnerType_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to QueryRunnerType values", s)
}

// QueryRunnerTypeValues returns all values of the enum
func QueryRunnerTypeValues() []QueryRunnerType {
	return _QueryRunnerType_values
}

// IsAQueryRunnerType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i QueryRunnerType) Registered() bool {
	for _, v := range _QueryRunnerType_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_QueryRunnerType_value = func() (val QueryRunnerType) { return }()

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_QueryRunnerType_value

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_QueryRunnerType_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for QueryRunnerType
func (i QueryRunnerType) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for QueryRunnerType
func (i *QueryRunnerType) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseQueryRunnerTypeString(string(data))
	return err
}

func _() {
	var _nil_QueryRunnerType_value = func() (val QueryRunnerType) { return }()

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_QueryRunnerType_value

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_QueryRunnerType_value
}

// MarshalJSON implements the json.Marshaler interface for QueryRunnerType
func (i QueryRunnerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for QueryRunnerType
func (i *QueryRunnerType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("QueryRunnerType should be a string, got %s", data)
	}

	var err error
	*i, err = ParseQueryRunnerTypeString(s)
	return err
}

func _() {
	var _nil_QueryRunnerType_value = func() (val QueryRunnerType) { return }()

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_QueryRunnerType_value

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_QueryRunnerType_value
}

// MarshalText implements the encoding.TextMarshaler interface for QueryRunnerType
func (i QueryRunnerType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for QueryRunnerType
func (i *QueryRunnerType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseQueryRunnerTypeString(string(text))
	return err
}

//func _() {
//	var _nil_QueryRunnerType_value = func() (val QueryRunnerType) { return }()
//
//	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_QueryRunnerType_value
//
//	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_QueryRunnerType_value
//}

// MarshalYAML implements a YAML Marshaler for QueryRunnerType
func (i QueryRunnerType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for QueryRunnerType
func (i *QueryRunnerType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseQueryRunnerTypeString(s)
	return err
}

func _() {
	var _nil_QueryRunnerType_value = func() (val QueryRunnerType) { return }()

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_QueryRunnerType_value

	// An "cannot convert QueryRunnerType literal (type QueryRunnerType) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_QueryRunnerType_value
}

func (i QueryRunnerType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *QueryRunnerType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseQueryRunnerTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// QueryRunnerTypeSliceContains reports whether sunEnums is within enums.
func QueryRunnerTypeSliceContains(enums []QueryRunnerType, sunEnums ...QueryRunnerType) bool {
	var seenEnums = map[QueryRunnerType]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// QueryRunnerTypeSliceContainsAny reports whether any sunEnum is within enums.
func QueryRunnerTypeSliceContainsAny(enums []QueryRunnerType, sunEnums ...QueryRunnerType) bool {
	var seenEnums = map[QueryRunnerType]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
