name: manual_release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        required: true
        type: string

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/release
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
